# Generated by Django 2.2.1 on 2019-10-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('satellite_type', models.CharField(max_length=25, verbose_name='Satellite Type')),
                ('name', models.CharField(help_text='Satellite Name', max_length=50, verbose_name='Name')),
                ('description', models.TextField(help_text='Satellite Description', verbose_name='Description')),
                ('launch_date', models.DateField(verbose_name='Launch Date')),
            ],
        ),
    ]
